# Generated by Django 4.2.3 on 2023-12-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.TextField(blank=True, null=True)),
                ("private_key", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nodes",
            fields=[
                (
                    "node",
                    models.URLField(primary_key=True, serialize=False, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                ("recipient", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                ("signature", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("timestamp", models.CharField(max_length=255)),
                ("proof", models.IntegerField()),
                ("previous_hash", models.CharField(max_length=256)),
                ("transactions", models.ManyToManyField(to="demo.transaction")),
            ],
        ),
    ]
