# Generated by Django 4.2.3 on 2024-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="signature",
            field=models.CharField(max_length=255),
        ),
    ]
