# Generated by Django 4.2.3 on 2024-01-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_alter_transaction_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="signature",
            field=models.BinaryField(),
        ),
    ]
